### ISSUE TITLE
file-error "Cannot open load file" "No such file or directory" "pallet"

### ISSUE THREAD

**Issue by jolin90** [andyque/Learning-Emacs#1]
GNU Emacs 25.1.1

Debugger entered--Lisp error: (file-error "Cannot open load file" "No such file or directory" "pallet")
  require(pallet)
  eval-buffer(#<buffer  *load*> nil "/home/jolin/.emacs.d/init.el" nil t)  ; Reading at buffer position 104
  load-with-code-conversion("/home/jolin/.emacs.d/init.el" "/home/jolin/.emacs.d/init.el" t t)
  load("/home/jolin/.emacs.d/init" t t)
  #[0 "\205\266	\306=\203\307\310Q\202?	\311=\204\307\312Q\202?\313\307\314\315#\203*\316\202?\313\307\314\317#\203>\320\321\322!D\nB\323\202?\316\324\325\324\211#\210\324=\203e\326\327\330\307\331Q!\"\325\324\211#\210\324=\203d\210\203\247\332!\333\232\203\247\334!\211\335P\336!\203\201\211\202\214\336!\203\213\202\214\314\262\203\245\337\"\203\243\340\341#\210\342\343!\210\266\f?\205\264\314\325\344\324\211#)\262\207" [init-file-user system-type delayed-warnings-list user-init-file inhibit-default-init inhibit-startup-screen ms-dos "~" "/_emacs" windows-nt "/.emacs" directory-files nil "^\\.emacs\\(\\.elc?\\)?$" "~/.emacs" "^_emacs\\(\\.elc?\\)?$" initialization format-message "`_emacs' init file is deprecated, please use `.emacs'" "~/_emacs" t load expand-file-name "init" file-name-as-directory "/.emacs.d" file-name-extension "elc" file-name-sans-extension ".el" file-exists-p file-newer-than-file-p message "Warning: %s is newer than %s" sit-for 1 "default"] 7]()
  command-line()
  normal-top-level()

pls !!!

**Comment by zilongshanren** [comment]
already fixed in latest head
