### ISSUE TITLE
init-funcs.el/zilongshanren-install-fonts 字体安装的问题

### ISSUE THREAD

**Issue by tmhourglass** [andyque/Learning-Emacs#6]
我这边在windows下，打算长期使用你的这个配置学习并使用。遇到个问题，想咨询下：这里面的url （/files/6135060/symbola.zip) 这个找不到，安装的时候报错。使用的字体我看在init-ui.el中的set-face-attribute也没有设置

modeline中的图标显示乱码

**Comment by tmhourglass** [comment]
Sloved!    NFM.ttf

**Comment by zilongshanren** [comment]
解决就好。
