### ISSUE TITLE
环境变量获取的配置问题

### ISSUE THREAD

**Issue by tmhourglass** [andyque/Learning-Emacs#7]
https://github.com/zilongshanren/.emacs.d/blob/a654d8f3dd3cbfcb58a78295bc3e6a13f6b09d59/lisp/init-basic.el#L135C16-L135C16

@zilongshanren 这个地方发现个bug，"-l" 应该改为 "-i"，即Non-interactive

---------
在使用eglot时找不到lsp，图标启动死活不行，命令启动正常，来来回回折腾了一下午，通过各种配置以及不同的启动方式调试，差点在emacs-china发贴求助，最终发现 (getenv "PATH")有问题，找到了exec-path-from-shell，此配置也配置了，仔细看了readme才发现这个小问题，终于解决，eglot也正常了

😅

**Comment by zilongshanren** [comment]
多谢谢提醒，已经修改。

**Comment by zilongshanren** [comment]
去掉这个选项，Emacs的启动时间会变长。 详细可以参考  exec-path-from-shell 的文档，我这边改用 non-interactive 的方式也可以正常加载lsp

**Comment by tmhourglass** [comment]
恩，非交互式可以加快启动时间。不过好像还是拼写错误呢
